server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/p2bhaskar/major_project_config.git
          clone-on-start: true

management:
  security:
    enabled: false


eureka:
  client:
    service-url:
      defaultZone:http: //localhost:8761/eureka
